version: '3.7'
services:
  dflask:
    build: .
    ports: 
      - 5000:5000

  dfmysql:
    image: mysql:8.0.33
    volumes:
      - /home/tslima/Documentos/alura/docker/mysql:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root